name: Continuous integration
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]
jobs:
  client_test_job:
    name: Client test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  server_test_job:
    name: Server test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4